Hosts:
  backend: :29001
Connections:
  default:
    Txt: mongodb://localhost:27017/datapipe 
    PoolSize: 10
EventServer:
  Server: nats://localhost:4222
  Group: KanoDataPipe2020
  EventChangeTopic: /config/change
Data:
  smtp_server: smtp.office365.com
  smtp_port: 587
  smtp_uid: no-reply@kanosolution.com
  smtp_password: KnxNP5aO
  smtp_tls: true
  jwt_method: HS256
  jwt_secret: CoronaVirusBerhentilah
  jwt_get_topic: /v1/iam/get
